package com.anker.expressfeeprarate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BasicData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String date_month;
	private java.lang.String allocation_by;
	private double amount;

	public BasicData() {
	}

	public java.lang.String getDate_month() {
		return this.date_month;
	}

	public void setDate_month(java.lang.String date_month) {
		this.date_month = date_month;
	}

	public java.lang.String getAllocation_by() {
		return this.allocation_by;
	}

	public void setAllocation_by(java.lang.String allocation_by) {
		this.allocation_by = allocation_by;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public BasicData(java.lang.String date_month,
			java.lang.String allocation_by, double amount) {
		this.date_month = date_month;
		this.allocation_by = allocation_by;
		this.amount = amount;
	}

}