package com.anker.expressfeeprarate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HcInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String date_month;
	private double hc;
	private double rate1;

	private java.lang.String bg_pdt;

	private double rate2;

	private double fee;

	public HcInfo() {
	}

	public java.lang.String getDate_month() {
		return this.date_month;
	}

	public void setDate_month(java.lang.String date_month) {
		this.date_month = date_month;
	}

	public double getHc() {
		return this.hc;
	}

	public void setHc(double hc) {
		this.hc = hc;
	}

	public double getRate1() {
		return this.rate1;
	}

	public void setRate1(double rate1) {
		this.rate1 = rate1;
	}

	public java.lang.String getBg_pdt() {
		return this.bg_pdt;
	}

	public void setBg_pdt(java.lang.String bg_pdt) {
		this.bg_pdt = bg_pdt;
	}

	public double getRate2() {
		return this.rate2;
	}

	public void setRate2(double rate2) {
		this.rate2 = rate2;
	}

	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	public HcInfo(java.lang.String date_month, double hc, double rate1,
			java.lang.String bg_pdt, double rate2, double fee) {
		this.date_month = date_month;
		this.hc = hc;
		this.rate1 = rate1;
		this.bg_pdt = bg_pdt;
		this.rate2 = rate2;
		this.fee = fee;
	}

}