package com.anker.expressfeeprarate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rate1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double totalHc;

	private java.lang.String date_month;

	public Rate1() {
	}

	public java.lang.String getDate_month() {
		return this.date_month;
	}

	public void setDate_month(java.lang.String date_month) {
		this.date_month = date_month;
	}

	public double getTotalHc() {
		return this.totalHc;
	}

	public void setTotalHc(double totalHc) {
		this.totalHc = totalHc;
	}

	public Rate1(double totalHc, java.lang.String date_month) {
		this.totalHc = totalHc;
		this.date_month = date_month;
	}

}